### ISSUE TITLE
Issues with templating

### ISSUE THREAD

**Issue by herrniemand** [gavinwahl/django-u2f#17]
TemplateDoesNotExist at /u2f/keys/
base.html
Request Method:	GET
Request URL:	https://localhost:8000/u2f/keys/
Django Version:	1.9.6
Exception Type:	TemplateDoesNotExist
Exception Value:	
base.html
Exception Location:	/home/niemand/Development/Django/u2f_django_nzpug/venv/lib/python3.5/site-packages/django/template/engine.py in find_template, line 169
Python Executable:	/home/niemand/Development/Django/u2f_django_nzpug/venv/bin/python
Python Version:	3.5.1
Python Path:	
['/home/niemand/Development/Django/u2f_django_nzpug',
 '/home/niemand/Development/Django/u2f_django_nzpug/venv/lib/python35.zip',
 '/home/niemand/Development/Django/u2f_django_nzpug/venv/lib/python3.5',
 '/home/niemand/Development/Django/u2f_django_nzpug/venv/lib/python3.5/plat-linux',
 '/home/niemand/Development/Django/u2f_django_nzpug/venv/lib/python3.5/lib-dynload',
 '/usr/lib64/python3.5',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-linux',
 '/home/niemand/Development/Django/u2f_django_nzpug/venv/lib/python3.5/site-packages']
Server time:	Thu, 12 May 2016 04:40:41 +0000
Template-loader postmortem

Django tried loading these templates, in this order:

Using engine django:
django.template.loaders.app_directories.Loader: /home/niemand/Development/Django/u2f_django_nzpug/venv/lib/python3.5/site-packages/django/contrib/admin/templates/base.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/niemand/Development/Django/u2f_django_nzpug/venv/lib/python3.5/site-packages/django/contrib/auth/templates/base.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/niemand/Development/Django/u2f_django_nzpug/venv/lib/python3.5/site-packages/django_u2f/templates/base.html (Source does not exist)

**Comment by gavinwahl** [comment]
Hi,

This is happening because the default templates expect there to be a `base.html` that they can inherit from. You should provided a `base.html` in your project, or override the default templates.
