### ISSUE TITLE
{"errorCode":2}

### ISSUE THREAD

**Issue by darkpixel** [gavinwahl/django-u2f#18]
The ```/add-key/``` page displays the text:
```
To add a security key to your account, insert (and tap) it.

Error with U2F
```

With a textbox below it containing the text:
```{"errorCode":2}```

My key works for signing in to Google, Github, etc...so I don't think it's a key problem.

I don't get any errors in the Django console or the Chrome console.

**Comment by gavinwahl** [comment]
Are you testing with a HTTP site? You must be on an HTTPS site to use u2f at all.

**Comment by darkpixel** [comment]
I'm testing in my local dev environment using http://localhost:8000/.  Hmm...I'll get Nginx set up in front of my django dev server and test that way.  Thanks.

**Comment by gavinwahl** [comment]
nginx will work, but there are also instructions in the readme about how to get https with runserver.

**Comment by darkpixel** [comment]
I see it now.  I skipped over the demo section because I wasn't trying to run the demo, I was trying to test it in my existing app.  I should have read closer.  Thanks for the kick.
