### ISSUE TITLE
Custom URL paths with Django-U2F

### ISSUE THREAD

**Issue by justinmayer** [gavinwahl/django-u2f#26]
I prefer to have more control over URL hierarchy. For example, I would prefer that the `u2f:login` view be served via `/login/` instead of `/u2f/login/`, with the rest of the U2F-related URLs available underneath `/settings/security/`. I also would like the ability to customize the URL slugs of some of the U2F views. In an effort to accomplish this, I currently use:
```
u2f_urls = [
    url(r'^multi-factor/', u2f_views.two_factor_settings,
        name='two-factor-settings'),
    url(r'^add-key/', u2f_views.add_key, name='add-u2f-key'),
    url(r'^verify-factor/', u2f_views.verify_second_factor,
        name='verify-second-factor'),
    url(r'^keys/', u2f_views.keys, name='u2f-keys'),
    url(r'^backup-codes/', u2f_views.backup_codes, name='backup-codes'),
    url(r'^add-totp-device/', u2f_views.add_totp, name='add-totp'),
    url(r'^totp-devices/', u2f_views.totp_devices, name='totp-devices'),
]

urlpatterns = [
    url(r'^login/', u2f_views.login, name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(
        next_page=reverse_lazy('login')),
        name='logout'),

    url(r'^settings/security/', include(u2f_urls, namespace='u2f')),
    [...]
```

Question 1: Is there a better way to handle this?

Question 2... In certain rare cases, there will be an unauthenticated request for the `verify-second-factor` view, which is handled by [this bit of code](https://github.com/gavinwahl/django-u2f/blob/efb41169d7802b58d0b5dc2c406fc92f69b68b6a/django_u2f/views.py#L162), which yields a `NoReverseMatch ` error because the `u2f:login` route doesn't exist in my setup above.

I suppose I could add a duplicate `login` entry in the top stanza so that `u2f:login` exists, but then I've got redundant login routes at `/login/` and `/settings/security/login/`.

My understanding of Django URL route namespaces is admittedly quite limited, but I can't quite think of the best way to handle this. Might you have any suggestions?

**Comment by gavinwahl** [comment]
1. You've got the normal way to handle this.

2. You can fix your namespace problem by doing something like this (untested, not sure if II have the arguments right off the top of my head):
    
    ```python
    u2f_urls = [
        url(r'^login/', u2f_views.login, name='login'),
        url(r'^settings/security', include([
            url(r'^multi-factor/', u2f_views.two_factor_settings,
                name='two-factor-settings'),
            url(r'^add-key/', u2f_views.add_key, name='add-u2f-key'),
            url(r'^verify-factor/', u2f_views.verify_second_factor,
                name='verify-second-factor'),
            url(r'^keys/', u2f_views.keys, name='u2f-keys'),
            url(r'^backup-codes/', u2f_views.backup_codes, name='backup-codes'),
            url(r'^add-totp-device/', u2f_views.add_totp, name='add-totp'),
            url(r'^totp-devices/', u2f_views.totp_devices, name='totp-devices'),
        ])),
    ]

    urlpatterns = [
        url(r'^', include(u2f_urls, namespace='u2f')
        url(r'^logout/$', auth_views.LogoutView.as_view(
            next_page=reverse_lazy('login')),
            name='logout'),

        [...]
   ```

**Comment by justinmayer** [comment]
Nested includes... Perfect! That never occurred to me.

This was extremely helpful, Gavin. Thank you SO much for the assistance... and for responding so quickly. You rock! 😁
