### ISSUE TITLE
Attestation signature verification failed (testproj)

### ISSUE THREAD

**Issue by mjjohnson** [gavinwahl/django-u2f#4]
I set up the demo project, and after logging in I tried to add a key, but got the error "Attestation signature verification failed!" (from `u2flib_server`).

To try to figure out what was going wrong, I tried doing the process manually: I started up `u2f_server.py` from `python-u2flib-server` (as described in [their README](https://github.com/Yubico/python-u2flib-server)) and used `curl` to hit the enroll endpoint and get a challenge. I used the JS API (from the Chrome extension) to send the challenge to my key and get the response data, which I submitted to `u2f_server.py` using `curl` again...and it worked. (My key is also working in Gmail and [Yubico's demo](http://demo.yubico.com/u2f).)

I stepped through `u2f.complete_register` for both the successful (manual) request as well as the unsuccessful one from the test project, and didn't spot a problem... Do you know what might be going wrong?

**Comment by mjjohnson** [comment]
Ah, I think I tracked it down. It was my problem, nothing to do with your project. I set up a fresh Ubuntu Server 14.04 VM and the test project worked perfectly. After doing some searching online, it looked like the version of OpenSSL I have on my system might have been the issue, and compiling the most recent version of that (and recompiling M2Crypto) fixed my issues. (I'm on a Mac, running OS X 10.9 Mavericks.)

For anyone else who runs into this issue while trying to run this (or any other M2Crypto-related issues) on Mac, here's what I did to solve it. (Note: I tried the homebrew version of openssl, but for some reason it wouldn't work at all with M2Crypto, so I uninstalled it and did the following instead.)

I downloaded [the latest OpenSSL](https://www.openssl.org/source/) and compiled it manually:

```bash
# Build 32-bit version
./config --prefix=$HOME
make && make install
# Build 64-bit version (need both versions for M2Crypto)
make clean && make dclean
./Configure darwin64-x86_64-cc --prefix=$HOME/ssl-x64
make && make install
```

Then I built "fat" libraries that combined the 32-bit and 64-bit versions:

```bash
lipo -create lib/libcrypto.a ssl-x64/lib/libcrypto.a -output lib/libcrypto.a
lipo -create lib/libssl.a ssl-x64/lib/libssl.a -output lib/libssl.a
```

Then I [downloaded](https://github.com/martinpaljak/M2Crypto), compiled, and installed M2Crypto manually:

```bash
python setup.py build build_ext --openssl=$HOME
python setup.py install build_ext --openssl=$HOME
```

Then, when I followed the rest of your instructions (`pip install -e .`, etc.), and fired up the server, everything worked. (The reason it worked when I ran it "manually" before is that I was running `u2f_server.py` on a Linux box while the simple HTML was on my local machine, to avoid port conflicts...which is an obvious mistake in hindsight.)

Sources: I cobbled together this solution from [here](https://stackoverflow.com/questions/25530429/build-multiarch-openssl-on-os-x) and [here](http://jonatkinson.co.uk/2008/10/09/installing-m2crypto-osx/).

**Comment by gavinwahl** [comment]
Great, glad you figured it out. Looks like M2Crypto could use some better error reporting? It seems like you can't tell the difference between an invalid certificate and an invalid install of the package?

**Comment by mjjohnson** [comment]
Something like that... Maybe the issue had to do with the CAs that were installed, or something? Or maybe some defaults changed? (Just guessing here.) On top of that, I'm not completely sure which version of OpenSSL was getting used by default: `which openssl` returns the version bundled with Postgres.app, so it may well have been that one getting used rather than the one installed with OS X 10.9.
